version: '3.8'

services:
  backend:
    build: ./backend
    container_name: sl-backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend/sl_enterprise.db:/app/sl_enterprise.db
      - ./backend/uploads:/app/uploads

  frontend:
    build: ./frontend
    container_name: sl-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
